/* ======================================================================
   PRY2205 – S8 (FORMA C) – SOLUCIÓN DE ACTIVIDAD SUMATIVA
   APLICANDO CONTROL DE ACCESO Y OPTIMIZACIÓN DE SENTENCIAS SQL

   >>> INSTRUCCIÓN DE EJECUCIÓN INICIAL <<<
   1. Conectar manualmente la sesión como usuario ADMINISTRATIVO (SYSTEM o SYS AS SYSDBA)
      a la PDB (XEPDB1) antes de iniciar la ejecución del script.
   2. Ejecutar el script completo para garantizar la configuración secuencial de objetos.

   ====================================================================== */

SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT FAILURE;

-- ======================================================================
-- SECCIÓN 1: USUARIO ADMINISTRATIVO (SYS / SYSTEM)
-- CASO 1: ESTRATEGIA DE SEGURIDAD (Creación de Usuarios, Roles y Privilegios)
-- ======================================================================

-- NOTA: Esta sección asume la conexión previa como usuario administrativo.

-- 1.1 CONFIGURACION DE AMBIENTE Y CREACION DE USUARIOS Y ROLES
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Creación segura de PRY2205_USER1 (Dueño de Objetos / Constructor)
BEGIN
  EXECUTE IMMEDIATE '
    CREATE USER PRY2205_USER1 IDENTIFIED BY "PRY2205.User1"
    DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS
  ';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE USER PRY2205_USER2 IDENTIFIED BY "PRY2205.User2"
    DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS
  ';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -01920 THEN RAISE; END IF;
END;
/

-- Creación de roles (Método seguro)
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE PRY2205_ROL_D'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -01921 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE ROLE PRY2205_ROL_P'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -01921 THEN RAISE; END IF; END;
/

-- Asignación de roles y privilegios de sistema
GRANT CREATE SESSION TO PRY2205_USER1, PRY2205_USER2;
GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;
ALTER USER PRY2205_USER1 DEFAULT ROLE PRY2205_ROL_D;
ALTER USER PRY2205_USER2 DEFAULT ROLE PRY2205_ROL_P;

-- Privilegios de sistema a roles
GRANT CREATE TABLE, CREATE VIEW, CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO PRY2205_ROL_P;

PROMPT 1.2 GRANTS DE OBJETO Y SINONIMOS PUBLICOS

-- Grants de objeto al rol de PROCESOS (PRY2205_ROL_P necesita SELECT en tablas de USER1)
GRANT SELECT ON PRY2205_USER1.LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.ALUMNO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.CARRERA TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.REBAJA_MULTA TO PRY2205_ROL_P;

-- Creación de sinónimos públicos
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM LIBRO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM EJEMPLAR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM PRESTAMO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM ALUMNO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM CARRERA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM REBAJA_MULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE PUBLIC SYNONYM LIBRO FOR PRY2205_USER1.LIBRO;
CREATE PUBLIC SYNONYM EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE PUBLIC SYNONYM PRESTAMO FOR PRY2205_USER1.PRESTAMO;
CREATE PUBLIC SYNONYM ALUMNO FOR PRY2205_USER1.ALUMNO;
CREATE PUBLIC SYNONYM CARRERA FOR PRY2205_USER1.CARRERA;
CREATE PUBLIC SYNONYM REBAJA_MULTA FOR PRY2205_USER1.REBAJA_MULTA;



----------------------------------------------------------------
-- SECCIÓN 2: USUARIO PRY2205_USER2
-- CASO 2: CREACIÓN DE INFORME CONTROL_STOCK_LIBROS
----------------------------------------------------------------

-- Requiere conexión como PRY2205_USER2
-- CONNECT PRY2205_USER2/"PRY2205.User2";

-- Limpieza de objetos de esquema local
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTROL_STOCK_LIBROS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTROL_STOCK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1) TABLA
CREATE TABLE CONTROL_STOCK_LIBROS (
  ID_CONTROL          NUMBER(10),
  LIBROID             NUMBER(5),
  NOMBRE_LIBRO        VARCHAR2(70),
  TOTAL_EJEMPLARES    NUMBER,
  EN_PRESTAMO         NUMBER,
  DISPONIBLES         NUMBER,
  PORCENTAJE_PRESTAMO VARCHAR2(10),
  STOCK_CRITICO       CHAR(1)
);

-- 2) SECUENCIA
CREATE SEQUENCE SEQ_CONTROL_STOCK
START WITH 1 INCREMENT BY 1;

-- 3) INSERT (AÑO COMPLETO – DOS AÑOS ATRÁS)
INSERT INTO CONTROL_STOCK_LIBROS
SELECT
  SEQ_CONTROL_STOCK.NEXTVAL,
  q.LIBROID,
  q.NOMBRE_LIBRO,
  q.TOTAL_EJEMPLARES,
  q.EN_PRESTAMO,
  q.DISPONIBLES,
  q.PORCENTAJE_PRESTAMO,
  q.STOCK_CRITICO
FROM (
  SELECT
    l.LIBROID,
    l.NOMBRE_LIBRO,
    tot.total_ejemplares                         AS TOTAL_EJEMPLARES,
    pre.ejemplares_prestados                     AS EN_PRESTAMO,
    (tot.total_ejemplares - pre.ejemplares_prestados) AS DISPONIBLES,
    -- CORRECCIÓN APLICADA: Usamos RTRIM para eliminar la coma final (,) 
    -- si el porcentaje es un número entero (ej: 50 se convierte de "50," a "50")
    RTRIM(
      TO_CHAR(
        ROUND((pre.ejemplares_prestados / tot.total_ejemplares) * 100, 2),
        'FM999D99',
        'NLS_NUMERIC_CHARACTERS='',.'''
      ),
      ','
    )                                            AS PORCENTAJE_PRESTAMO,
    CASE
      WHEN (tot.total_ejemplares - pre.ejemplares_prestados) > 2 THEN 'S'
      ELSE 'N'
    END                                          AS STOCK_CRITICO
  FROM LIBRO l
  JOIN (
      SELECT LIBROID, COUNT(*) total_ejemplares
      FROM EJEMPLAR
      GROUP BY LIBROID
  ) tot ON tot.LIBROID = l.LIBROID
  JOIN (
      SELECT LIBROID, COUNT(*) ejemplares_prestados
      FROM PRESTAMO
      WHERE EMPLEADOID IN (190,180,150)
        AND EXTRACT(YEAR FROM FECHA_INICIO) = EXTRACT(YEAR FROM SYSDATE) - 2
      GROUP BY LIBROID
  ) pre ON pre.LIBROID = l.LIBROID
  ORDER BY l.LIBROID
) q;

COMMIT;

-- RESULTADO FINAL DE VERIFICACIÓN
SELECT *
FROM CONTROL_STOCK_LIBROS
ORDER BY LIBROID;



----------------------------------------------------------------
-- SECCIÓN 3: USUARIO PRY2205_USER1
-- CASO 3.1: VISTA VW_DETALLE_MULTAS
-- CASO 3.2: ÍNDICE DE OPTIMIZACIÓN
----------------------------------------------------------------

-- Requiere conexión como PRY2205_USER1
-- CONNECT PRY2205_USER1/"PRY2205.User1";

-- CASO 3.1: VISTA VW_DETALLE_MULTAS

-- Eliminación segura de la vista

BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW VW_DETALLE_MULTAS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -00942 THEN RAISE; END IF;
END;
/

-- Creación de la vista VW_DETALLE_MULTAS con formato y orden final (Usando Valor de Multa como desempate)
CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
    P.PRESTAMOID AS ID_PRESTAMO,
    
    -- CORRECCIÓN 1: Nombre y solo el Apellido Paterno (NOMBRE APELLIDO)
    A.NOMBRE || ' ' || A.APATERNO AS NOMBRE_ALUMNO,
    
    C.DESCRIPCION AS NOMBRE_CARRERA,
    L.LIBROID AS ID_LIBRO,
    
    -- VALOR_LIBRO: Formato $XX.XXX,00
    TO_CHAR(L.PRECIO, 'FM$999G999D00', 'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_LIBRO,
    
    -- FECHAS: Formato DD/MM/RRRR
    TO_CHAR(P.FECHA_TERMINO, 'DD/MM/RRRR') AS FECHA_TERMINO,
    TO_CHAR(P.FECHA_ENTREGA, 'DD/MM/RRRR') AS FECHA_ENTREGA,
    
    -- Días de Atraso
    TRUNC(P.FECHA_ENTREGA - P.FECHA_TERMINO) AS DIAS_ATRASO,
    
    -- Multa Base Numérica (para usarla en el ORDER BY)
    TRUNC(L.PRECIO * 0.03 * (P.FECHA_ENTREGA - P.FECHA_TERMINO)) AS MULTA_BASE_NUM,

    -- VALOR_MULTA: Multa Base formateada $XX.XXX
    TO_CHAR(
        TRUNC(L.PRECIO * 0.03 * (P.FECHA_ENTREGA - P.FECHA_TERMINO)), 
        'FM$999G999', 
        'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_MULTA,

    -- CORRECCIÓN 2: PORCENTAJE_REBAJA_MULTA: Formato '0' si no hay descuento
    CASE
        WHEN NVL(RM.PORC_REBAJA_MULTA, 0) = 0 THEN '0' -- Cambiado de '0,' a '0'
        ELSE TO_CHAR(
                 NVL(RM.PORC_REBAJA_MULTA, 0) / 100,
                 'FM0D99', 
                 'NLS_NUMERIC_CHARACTERS='',.'''
             )
    END AS PORCENTAJE_REBAJA_MULTA,
    
    -- VALOR_REBAJADO: Valor neto después de aplicar la rebaja, formateado $XX.XXX
    TO_CHAR(
        TRUNC(
            TRUNC(L.PRECIO * 0.03 * (P.FECHA_ENTREGA - P.FECHA_TERMINO)) * (1 - NVL(RM.PORC_REBAJA_MULTA, 0) / 100)
        ),
        'FM$999G999', 
        'NLS_NUMERIC_CHARACTERS='',.''') AS VALOR_REBAJADO
FROM
    PRESTAMO P      
JOIN
    ALUMNO A ON P.ALUMNOID = A.ALUMNOID
JOIN
    CARRERA C ON A.CARRERAID = C.CARRERAID
JOIN
    LIBRO L ON P.LIBROID = L.LIBROID
LEFT JOIN
    REBAJA_MULTA RM ON C.CARRERAID = RM.CARRERAID 
WHERE
    -- Filtro 1: Préstamos terminados hace 2 años
    EXTRACT(YEAR FROM P.FECHA_TERMINO) = (EXTRACT(YEAR FROM SYSDATE) - 2)
    -- Filtro 2: Entregados con atraso
    AND P.FECHA_ENTREGA > P.FECHA_TERMINO
    AND P.FECHA_ENTREGA IS NOT NULL
ORDER BY
    P.FECHA_ENTREGA DESC,
    MULTA_BASE_NUM DESC; -- Criterio de desempate por multa más alta




-- RESULTADO FINAL DE LA VISTA
SELECT ID_PRESTAMO, NOMBRE_ALUMNO, NOMBRE_CARRERA, ID_LIBRO, VALOR_LIBRO, 
       FECHA_TERMINO, FECHA_ENTREGA, DIAS_ATRASO, VALOR_MULTA, 
       PORCENTAJE_REBAJA_MULTA, VALOR_REBAJADO
FROM VW_DETALLE_MULTAS;



-- =================================================================================
-- CASO 3.2: CREACIÓN DE ÍNDICES PARA OPTIMIZACIÓN (Método Seguro)
-- =================================================================================

-- 1. ELIMINACIÓN SEGURA del índice si ya existe (para evitar ORA-00955)

-- CONECTAR COMO PRY2205_USER1 Descomentar la siguiente línea si es necesario
-- CONNECT PRY2205_USER1/"PRY2205.User1";

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_PRESTAMO_MULTA_OPT';
EXCEPTION
    WHEN OTHERS THEN
        -- ORA-01418: indica que el índice no existe, se ignora el error.
        IF SQLCODE != -01418 THEN RAISE; END IF;
END;
/

-- 2. CREACIÓN del índice
-- Optimiza el acceso al filtrar por FECHA_TERMINO y el ordenamiento por FECHA_ENTREGA DESC.
CREATE INDEX IDX_PRESTAMO_MULTA_OPT 
ON PRESTAMO (FECHA_TERMINO, FECHA_ENTREGA DESC);